export type IndianCity =
  | "Mumbai"
  | "Delhi"
  | "Noida"
  | "Gurgaon"
  | "Pune"
  | "Kolkata"
  | "Bengaluru"
  | "Jaipur"
  | "Ahmedabad"
  | "Chennai"

export type UserRole = "CupShup" | "Client" | "Vendor"

export type BrandName =
  | "Flipkart"
  | "DCB Bank"
  | "VLCC"
  | "Spencers"
  | "Unity Bank"
  | "Tata 1mg"
  | "Sleepwell"
  | "HDFC Life"
  | "Farmrise"
  | "Natures Basket"