// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdslyhsaebzabstxskgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkc2x5aHNhZWJ6YWJzdHhza2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMDM1MDMsImV4cCI6MjA1MTU3OTUwM30.gawd7hjk1VrPuRkStnKaSWCsr-LZanGM6t4Cl-KrDhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);